language: go

go:
  - 1.9
  - tip

env:
  - TBD=TBD

before_install:
  - sudo apt-get install autoconf automake libtool curl make g++ unzip
  - go get github.com/golang/protobuf/proto

install:
  - wget https://github.com/protocolbuffers/protobuf/releases/download/v3.9.1/protobuf-all-3.9.1.tar.gz
  - tar -xzvf protobuf-all-3.9.1.tar.gz
  - pushd protobuf-3.9.1 && ./configure --prefix=/usr && make && sudo make install && sudo ldconfig && popd

script:
  - go test -cpu=1,2 -v
